version: "3.8"
services:
  juno:
    build:
      context: .
      args:
        UPSTREAM_VERSION: v0.15.12
    image: juno.public.dappnode.eth:2.0.6
    security_opt:
      - seccomp:unconfined
    ports:
      - "6060:6060"
      - "6061:6061"
    environment:
      ETH_L1_RPC_URL: ws://execution.mainnet.staker.dappnode:8546
      SNAPSHOT_URL: https://juno-snapshots.nethermind.io/files/mainnet/latest
      NETWORK: mainnet
      ENABLE_WS: true
      WS_PORT: 6061
      WS_HOST: 0.0.0.0
      EXTRA_OPTS: ""
    volumes:
      - juno_data:/var/lib/juno
    restart: unless-stopped
  staking:
    image: nethermind/starknet-staking-v2:v0.2.9
    environment:
      PROVIDER_HTTP_URL: http://juno:6060/rpc/v0_10
      PROVIDER_WS_URL: ws://juno:6061/ws/v0_10
      SIGNER_OPERATIONAL_ADDRESS: ""
      SIGNER_PRIVATE_KEY: ""
      SIGNER_EXTERNAL_URL: ""
    restart: unless-stopped

volumes:
  juno_data: {}
