version: "3.8"
services:
  juno:
    build:
      context: .
      args:
        UPSTREAM_VERSION: v0.15.0
    image: juno.public.dappnode.eth:2.0.3
    security_opt:
      - seccomp:unconfined
    ports:
      - "6060:6060"
      - "6061:6061"
    environment:
      ETH_L1_RPC_URL: ws://execution.mainnet.staker.dappnode:8546
      SNAPSHOT_URL: https://juno-snapshots.nethermind.io/files/mainnet/latest
      NETWORK: mainnet
      ENABLE_WS: true
      WS_PORT: 6061
      WS_HOST: 0.0.0.0
      EXTRA_OPTS: ""
    volumes:
      - juno_data:/var/lib/juno
    restart: unless-stopped

volumes:
  juno_data: {}
